MapSymbolDefinitions.getInstance():addTexture("AdminRadZone_1", "media/ui/LootableMaps/AdminRadZone_128.png")
MapSymbolDefinitions.getInstance():addTexture("AdminRadZone_2", "media/ui/LootableMaps/AdminRadZone_256.png")
MapSymbolDefinitions.getInstance():addTexture("AdminRadZone_3", "media/ui/LootableMaps/AdminRadZone_512.png")
MapSymbolDefinitions.getInstance():addTexture("AdminRadZone_4", "media/ui/LootableMaps/AdminRadZone_1024.png")
MapSymbolDefinitions.getInstance():addTexture("AdminRadZone_5", "media/ui/LootableMaps/AdminRadZone_2400.png")
